services:

  faculte-discovery-servise:
    build: ./Discovery-Service
    container_name: faculte-discovery-servise
    ports:
      - '8761:8761'
    healthcheck:
      test: ["CMD","curl","http://localhost:8761/actuator/health"]
#      for test because service use many time for run
      interval: 30s
      retries: 4


  faculty-config-servise:
    build: ./Configuration_Service
    container_name: faculty-config-servise
    ports:
      - '9999:9999'
    environment:
      - DISCOVERY_SERVICE_URL=http://faculte-discovery-servise:8761/eureka
    healthcheck:
      test: [ "CMD","curl","http://faculty-config-servise:9999/actuator/health" ]
      #      for test because service use many time for run
      interval: 20s
      retries: 4
    depends_on:
       faculte-discovery-servise:
         condition: service_healthy

  faculty-gateway-servise:
    build: ./Gateway-Service
    container_name: faculty-gateway-servise
    ports:
      - '8888:8888'
    environment:
      - DISCOVERY_SERVICE_URL=http://faculte-discovery-servise:8761/eureka
    healthcheck:
      test: [ "CMD","curl","http://localhost:8888/actuator/health" ]
      #      for test because service use many time for run
      interval: 10s
      retries: 5
    depends_on:
      faculte-discovery-servise:
        condition: service_healthy


  faculty-security-servise:
    build: ./Security-Service
    container_name: faculty-security-servise
    ports:
      - '9090:9090'
    environment:
      - DISCOVERY_SERVICE_URL=http://faculte-discovery-servise:8761/eureka
    healthcheck:
      test: [ "CMD","curl","http://localhost:9090/actuator/health" ]
      #      for test because service use many time for run
      interval: 10s
      retries: 4
    depends_on:
      faculte-discovery-servise:
        condition: service_healthy


  #  data base postgres
  postgres:
    image: postgres:13.22-alpine3.22
    restart: always
    environment:
      POSTGRES_PASSWORD: 2001fati
      POSTGRES_USER: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data


  faculty-filiere-servise:
    build: ./Filiere_Service
    container_name: faculty-filiere-servise
    ports:
      - '8081:8081'
    environment:
      - CONFIG_SERVER_URL=http://faculty-config-servise:9999
      - DISCOVERY_SERVICE_URL=http://faculte-discovery-servise:8761/eureka

    healthcheck:
      test: [ "CMD","curl","http://faculty-filiere-servise:8081/actuator/health" ]
      #      for test because service use many time for run
      interval: 10s
      retries: 4
    depends_on:
      postgres:
        condition: service_healthy
      faculty-config-servise:
        condition: service_healthy
      faculte-discovery-servise:
        condition: service_healthy


  faculty-etudiant-servise:
    build: ./Etudiant_Service
    container_name: faculty_etudiant-servise
    ports:
      - '8082:8082'
    environment:
      - CONFIG_SERVER_URL=http://faculty-config-servise:9999
      - DISCOVERY_SERVICE_URL=http://faculte-discovery-servise:8761/eureka
    healthcheck:
      test: [ "CMD","curl","http://localhost:8082/actuator/health" ]
      #      for test because service use many time for run
      interval: 10s
      retries: 4
    depends_on:
      postgres:
        condition: service_healthy
      faculty-config-servise:
          condition: service_healthy
      faculte-discovery-servise:
        condition: service_healthy

volumes:
  pgdata:


